services:
  backend:
    image: gonzalobosio/chat-box-back:v1
    env_file:
      - .env
    ports:
      - "8000:8000"

  frontend:
    image: gonzalobosio/chat-box-front:v1
    env_file:
      - ./frontend/.env
    ports:
      - "8100:8100"
